# Generated by Django 2.2.5 on 2019-10-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=32)),
                ('last_message', models.CharField(max_length=65536)),
                ('is_group_chat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=65536)),
                ('added_at', models.DateField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.Chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.User')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_messages', models.CharField(max_length=32)),
                ('chat_id', models.ManyToManyField(to='chats.Chat')),
                ('last_read_message_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.User')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.Chat')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.Message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.User')),
            ],
        ),
    ]
