# Generated by Django 2.2.5 on 2019-11-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20191121_0006'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'attach', 'verbose_name_plural': 'attaches'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'chat', 'verbose_name_plural': 'chats'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='type_of',
            new_name='mime_type',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_read_message_id',
            new_name='last_read_message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='added_at',
        ),
        migrations.AddField(
            model_name='attachment',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.Chat'),
        ),
        migrations.AddField(
            model_name='member',
            name='chat',
            field=models.ManyToManyField(null=True, to='chats.Chat'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.User'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=65536, null=True),
        ),
    ]
