# Generated by Django 2.2.5 on 2019-12-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191203_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
